server:
  port: 8080
spring:
  application:
    name: "ShopSavvy"
  devtools:
    add-properties: false
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/shopsavvy"
    username: "root"
    password: "root"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    database-platform: "org.hibernate.dialect.MySQLDialect"
    hibernate:
      ddl-auto: "update"
   # properties:
     # hibernate:
       # format_sql: true
       # show_sql: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
bet_billions:
  url: https://betbillions.com.co/
  email:
    sender: corporate@betbillions.com.co
    password : Fara4020**
